### PR TITLE
English to Hindi Translation

### PR DESCRIPTION
**Pull request by div3xi**
The file has been translated from English to Hindi, This is the initial translation.

✨ Cheers

---

- [x] I understand that contributing to this repository will require me to agree with the [CLA](https://github.com/anyproto/.github/blob/main/docs/CLA.md)

---

### What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [x] :world_map: Localisation

### Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 [tech-docs](https://github.com/anyproto/tech-docs)
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by div3xi** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by div3xi** [comment]
recheck

**Comment by fuksman** [comment]
Hi @div3xi, please check for conflicts with the existing translation. 
It's possible to avoid the merging process if you provide translations via Crowdin. Please consider this option as well.

**Comment by fuksman** [comment]
@any contributor @div3xi l10n hi-IN

**Pull request merged**
