### PR TITLE
added pt-BR translations to 261 words/phrases

### PR DESCRIPTION
**Pull request by DaviidSantos**
---

- [x] I understand that contributing to this repository will require me to agree with the [CLA](https://github.com/anyproto/.github/blob/main/docs/CLA.md)

---

### What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [x] 🗺️ Localization

### Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 [tech-docs](https://github.com/anyproto/tech-docs)
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by DaviidSantos** [comment]
I hereby grant Any Association and its successors or assignees permission to use, copy, modify, distribute, and sub-license my contributions on any terms they like, under all my rights in my contributions. A contribution includes anything I submit to the project. I am giving them this license in order to make it possible for them to accept my contributions into their project.

As far as the law allows, my contributions come as is, without any warranty or condition, and I will not be liable to anyone for any damages related to this software or this license, under any kind of legal claim.

**Comment by DaviidSantos** [comment]
recheck

**Comment by DaviidSantos** [comment]
recheck

**Comment by DaviidSantos** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by fuksman** [comment]
@any contributor @DaviidSantos l10n pt-BR

**Pull request merged**
