### PR TITLE
New translations text.json (Norwegian)

### PR DESCRIPTION
**Pull request by langtind**
Hello, this is the initial version of the Norwegian translation for Anytype. I have translated all the strings from the English file to Norwegian, based on my best understanding of the context and meaning. However, I have not seen the translation in use, so some of them may be a little bit off when actually displayed in the software. 

I hope this is something you want and that it meets your quality standards. Please let me know if you have any feedback or suggestions for improvement. Thank you for your consideration.

### CODE REVIEW

**Comment by langtind** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by langtind** [comment]
recheck

**Comment by fuksman** [comment]
@langtind thank you!

**Comment by fuksman** [comment]
@langtind your translation is now available on https://crowdin.com/project/anytype-desktop, you can add new translations or updating existing there.

**Comment by fuksman** [comment]
@any contributor @langtind l10n nb-NO

**Pull request merged**
